# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ugbu5kYVcHapsyvFvKX-IhdPZ2k2rZXo
"""

import numpy as np
import pandas as pd

data = pd.read_csv("/content/book23.csv")
data['result']

from sklearn.preprocessing import LabelEncoder
obj = LabelEncoder()
new_result = data['result']
new_values = obj.fit_transform(new_result)
new_values

from sklearn.preprocessing import LabelBinarizer
obj = LabelBinarizer()
new_values1 = obj.fit_transform(new_result)
new_values1

actual = [1,1,1,0,0,1,0,0,0,1,0,1]
predict = [0,1,1,0,0,1,1,0,1,1,0,1]

from sklearn.metrics import accuracy_score
accuracy_score(actual,predict)

from sklearn.metrics import confusion_matrix
confusion_matrix(actual,predict)

from sklearn.metrics import classification_report
result = pd.DataFrame(classification_report(actual,predict,output_dict = True))
result