# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1csqOxw7RwqnW_pp1kMqZo2bZNp4jL3tq
"""

!pip install opendatasets
import opendatasets as od

!pip install legacy-cgi
import opendatasets as od
od.download("https://www.kaggle.com/datasets/himanshunakrani/iris-dataset")

import numpy as np
import pandas as pd
data = pd.read_csv("/content/iris-dataset/iris.csv")
data.head()

data.shape

data.describe()

data.info()

x = data.drop('species',axis = 1)
x.head()

y = data['species']
y.head()

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x = scaler.fit_transform(x)
x[0:6]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(x_train,y_train)

pred = model.predict(x_test)

correct = np.sum(pred==y_test)
print(correct)

pred

data = pd.DataFrame(data=[pred,y_test],index = ["Pred","Y-test"])
data.transpose()