# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KtK5TtSiOghW-I-v5MoqQKuvRYJD8B-V
"""

!pip install opendatasets

import opendatasets as od
od.download("https://www.kaggle.com/datasets/himanshunakrani/iris-dataset")

import opendatasets as od
od.download("https://www.kaggle.com/datasets/himanshunakrani/iris-dataset")

!pip install legacy-cgi

import opendatasets as od
od.download("https://www.kaggle.com/datasets/himanshunakrani/iris-dataset")

import pandas as pd
import numpy as np

data = pd.read_csv("/content/iris-dataset/iris.csv")
data.head()

x = data.iloc[:,1:4]
x

x.shape

x.info()

y = data.iloc[:,-1]
y

y.info()

from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
x = scale.fit_transform(x)
x[0:5]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

correct_sum = []
for i in range(1,20):
  from sklearn.neighbors import KNeighborsClassifier
  model = KNeighborsClassifier(n_neighbors=i)
  model.fit(x_train,y_train)
  pred = model.predict(x_test)
  correct = np.sum(pred == y_test)
  correct_sum.append(correct)
correct_sum

from sklearn.neighbors import KNeighborsClassifier
 model = KNeighborsClassifier(n_neighbors=10)
 model.fit(x_train,y_train)
 pred = model.predict(x_test)

count = np.sum(pred == y_test)
print(count)

pred[0:10]

data = pd.DataFrame(data=[y_test,pred],index=['Y_test','Predict'])
data.transpose()

data.info()