# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TKthN17nvv9hPdSj1_7eLkAO1wnY7uVN
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

data = pd.read_csv("/content/Book2.csv")
data

x_train,x_test,y_train,y_test = train_test_split(data[['Videos','days','Subscribe']],data.Views,test_size=0.2)

model = LinearRegression()
model.fit(x_train,y_train)

data[['Videos','days','Subscribe']]

x_test

y_test

new_predict = model.predict(x_test)
print(new_predict)

model.coef_

model.intercept_