# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ANMhAKFBMHWqKL6o0DZpXGQImMairVTw
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

import pandas as pd

data = pd.read_csv('/content/Book1.csv')
data

plt.plot(data.Vedios, data.Views, color='blue', linestyle='--', marker='o', label='Growth')
plt.title('Linear regression')
plt.xlabel('Vedios')
plt.ylabel('Views')
plt.legend()
plt.grid(True)

plt.show()

x = np.array(data.Vedios).reshape(-1, 1)
y = np.array(data.Views)
model = LinearRegression()
model.fit(x, y)

x_new = np.array([45]).reshape(-1,1)
y_predict = model.predict(x_new)
print(y_predict)

plt.scatter(data.Vedios, data.Views, color='blue')
m,c= np.polyfit(x.reshape(-1 ),y,1)
plt.plot(x, m*x+c, color='red')
plt.xlabel('Vedios')
plt.ylabel('Views')
plt.show()

m