# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TKthN17nvv9hPdSj1_7eLkAO1wnY7uVN
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

data = pd.read_csv("/content/Book2.csv")
data

model = LinearRegression()
model.fit(data[['Videos','days','Subscribe']],data.Views)

data[['Videos','days','Subscribe']]





new_views = np.array([[50,199,4500]])
new_predict = model.predict(new_views)
print(new_predict)

model.coef_

model.intercept_